/**
 * 
 */
package cams7.siscom.ui;

import static javax.swing.KeyStroke.getKeyStroke;

import java.awt.Color;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.net.URL;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JSeparator;
import javax.swing.JToolBar;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

import org.springframework.stereotype.Component;

import cams7.apps.desk.util.AppResourceBundleMessage;
import cams7.apps.util.ApplicationUtil;

/**
 * @author cesar
 *
 */
@Component
public class MenuView extends JFrame {

	private static final long serialVersionUID = 1L;

	// Variables declaration - do not modify
	private JButton btnCadastroCliente;
	private JButton btnCadastroFornecedor;
	private JButton btnCadastroProduto;
	private JButton btnContasPagar;
	private JButton btnContasReceber;
	private JButton btnSair;
	private JLabel jLabel1;
	private JMenu jMenu1;
	private JMenuBar jMenuBar1;
	private JPanel jPanel1;
	private JPanel jPanel2;
	private JPopupMenu.Separator jSeparator1;
	private JPopupMenu.Separator jSeparator2;
	private JPopupMenu.Separator jSeparator3;
	private JPopupMenu.Separator jSeparator4;
	private JPopupMenu.Separator jSeparator5;
	private JSeparator jSeparator6;
	private JToolBar.Separator jSeparator7;
	private JToolBar.Separator jSeparator8;
	private JToolBar jToolBar1;

	private JMenuItem menuAtualizacaoPreco;
	private JMenu menuCadastro;
	private JMenuItem menuCadastroCartao;
	private JMenuItem menuCadastroCliente;
	private JMenuItem menuCadastroContaBancaria;
	private JMenuItem menuCadastroDepartamento;
	private JMenuItem menuCadastroFornecedor;
	private JMenuItem menuCadastroFuncionario;
	private JMenuItem menuCadastroPlanoConta;
	private JMenuItem menuCadastroProduto;
	private JMenuItem menuCadastroTipoPgtoRecebimento;
	private JMenuItem menuCadastroUnidade;
	private JMenuItem menuCalculadora;
	private JMenuItem menuCalendario;
	private JMenu menuCompras;
	private JMenuItem menuConciliacaoCheques;
	private JMenuItem menuConfirmacaoCotacao;
	private JMenuItem menuContasPagar;
	private JMenuItem menuContasReceber;
	private JMenu menuControleEstoque;
	private JMenuItem menuCotacao;
	private JMenuItem menuEmissaoCheques;
	private JMenuItem menuEntradaNF;
	private JMenu menuMovimento;
	private JMenuItem menuMovimentoBanco;
	private JMenuItem menuNivelAcesso;
	private JMenuItem menuPedido;
	private JMenuItem menuRequisicao;
	private JMenuItem menuSair;
	private JMenu menuSeguranca;
	private JMenuItem menuSenha;

	private JMenu menuTesourariaBanco;
	private JMenu menuUltilitarios;
	private JMenuItem menuVendas;

	private MenuAjuda menuAjuda;
	private JMenuItem menuSobre;

	private AppResourceBundleMessage bundleMessage;

	/**
	 * Creates new form Menu
	 */
	public MenuView() {
		super();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	public void initComponents(AppResourceBundleMessage bundleMessage) {

		this.bundleMessage = bundleMessage;

		jSeparator6 = new JSeparator();
		jMenu1 = new JMenu();
		jPanel1 = new JPanel();
		jToolBar1 = new JToolBar();
		btnCadastroCliente = new JButton();
		btnCadastroFornecedor = new JButton();
		btnCadastroProduto = new JButton();
		jSeparator7 = new JToolBar.Separator();
		btnContasPagar = new JButton();
		btnContasReceber = new JButton();
		jSeparator8 = new JToolBar.Separator();
		btnSair = new JButton();
		jPanel2 = new JPanel();
		jLabel1 = new JLabel();
		jMenuBar1 = new JMenuBar();
		menuCadastro = new JMenu();
		menuCadastroCliente = new JMenuItem();
		menuCadastroFornecedor = new JMenuItem();
		menuCadastroContaBancaria = new JMenuItem();
		jSeparator1 = new JPopupMenu.Separator();
		menuCadastroUnidade = new JMenuItem();
		menuCadastroProduto = new JMenuItem();
		jSeparator2 = new JPopupMenu.Separator();
		menuCadastroDepartamento = new JMenuItem();
		menuCadastroFuncionario = new JMenuItem();
		jSeparator3 = new JPopupMenu.Separator();
		menuCadastroCartao = new JMenuItem();
		menuCadastroPlanoConta = new JMenuItem();
		menuCadastroTipoPgtoRecebimento = new JMenuItem();
		jSeparator4 = new JPopupMenu.Separator();
		menuSair = new JMenuItem();
		menuMovimento = new JMenu();
		menuContasPagar = new JMenuItem();
		menuContasReceber = new JMenuItem();
		menuVendas = new JMenuItem();
		menuControleEstoque = new JMenu();
		menuEntradaNF = new JMenuItem();
		menuAtualizacaoPreco = new JMenuItem();
		menuCompras = new JMenu();
		menuRequisicao = new JMenuItem();
		menuCotacao = new JMenuItem();
		menuConfirmacaoCotacao = new JMenuItem();
		menuPedido = new JMenuItem();
		menuTesourariaBanco = new JMenu();
		menuEmissaoCheques = new JMenuItem();
		menuConciliacaoCheques = new JMenuItem();
		menuMovimentoBanco = new JMenuItem();
		menuUltilitarios = new JMenu();
		menuCalculadora = new JMenuItem();
		menuCalendario = new JMenuItem();
		jSeparator5 = new JPopupMenu.Separator();
		menuSeguranca = new JMenu();
		menuSenha = new JMenuItem();
		menuNivelAcesso = new JMenuItem();

		menuAjuda = new MenuAjuda();
		menuSobre = new JMenuItem();

		jSeparator6.setOrientation(SwingConstants.VERTICAL);

		jMenu1.setText("jMenu1");

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setTitle(getBundleMessage().getMessage("SisCom_title"));

		jPanel1.setBackground(new Color(204, 255, 255));

		jToolBar1.setBackground(new Color(102, 204, 255));
		jToolBar1.setRollover(true);

		btnCadastroCliente.setIcon(new ImageIcon(
				getURLImage("cadastro_cliente2.png"))); // NOI18N
		btnCadastroCliente.setToolTipText(getBundleMessage().getMessage(
				"MenuView.btnCadastroCliente.toolTipText"));
		btnCadastroCliente.setFocusable(false);
		btnCadastroCliente.setHorizontalTextPosition(SwingConstants.CENTER);
		btnCadastroCliente.setVerticalTextPosition(SwingConstants.BOTTOM);

		jToolBar1.add(btnCadastroCliente);

		btnCadastroFornecedor.setIcon(new ImageIcon(
				getURLImage("fornecedor2.png"))); // NOI18N
		btnCadastroFornecedor.setToolTipText(getBundleMessage().getMessage(
				"MenuView.btnCadastroFornecedor.toolTipText"));
		btnCadastroFornecedor.setFocusable(false);
		btnCadastroFornecedor.setHorizontalTextPosition(SwingConstants.CENTER);
		btnCadastroFornecedor.setVerticalTextPosition(SwingConstants.BOTTOM);

		jToolBar1.add(btnCadastroFornecedor);

		btnCadastroProduto.setIcon(new ImageIcon(
				getURLImage("cadastro_produto.png"))); // NOI18N
		btnCadastroProduto.setToolTipText(getBundleMessage().getMessage(
				"MenuView.btnCadastroProduto.toolTipText"));
		btnCadastroProduto.setFocusable(false);
		btnCadastroProduto.setHorizontalTextPosition(SwingConstants.CENTER);
		btnCadastroProduto.setVerticalTextPosition(SwingConstants.BOTTOM);
		jToolBar1.add(btnCadastroProduto);
		jToolBar1.add(jSeparator7);

		btnContasPagar.setIcon(new ImageIcon(getURLImage("contas_pagar2.png"))); // NOI18N
		btnContasPagar.setToolTipText(getBundleMessage().getMessage(
				"MenuView.btnContasPagar.toolTipText"));
		btnContasPagar.setFocusable(false);
		btnContasPagar.setHorizontalTextPosition(SwingConstants.CENTER);
		btnContasPagar.setVerticalTextPosition(SwingConstants.BOTTOM);
		jToolBar1.add(btnContasPagar);

		btnContasReceber.setIcon(new ImageIcon(
				getURLImage("contas_receber2.png"))); // NOI18N
		btnContasReceber.setToolTipText(getBundleMessage().getMessage(
				"MenuView.btnContasReceber.toolTipText"));
		btnContasReceber.setFocusable(false);
		btnContasReceber.setHorizontalTextPosition(SwingConstants.CENTER);
		btnContasReceber.setVerticalTextPosition(SwingConstants.BOTTOM);
		jToolBar1.add(btnContasReceber);
		jToolBar1.add(jSeparator8);

		btnSair.setIcon(new ImageIcon(getURLImage("sair2.png"))); // NOI18N
		btnSair.setToolTipText(getBundleMessage().getMessage(
				"MenuView.btnSair.toolTipText"));
		btnSair.setFocusable(false);
		btnSair.setHorizontalTextPosition(SwingConstants.CENTER);
		btnSair.setVerticalTextPosition(SwingConstants.BOTTOM);

		jToolBar1.add(btnSair);

		GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addComponent(jToolBar1,
				GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addComponent(jToolBar1,
				GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
				GroupLayout.PREFERRED_SIZE));

		jLabel1.setIcon(new ImageIcon(getURLImage("aperto_maos.png"))); // NOI18N
		jLabel1.setToolTipText(getBundleMessage().getMessage("SisCom_title"));

		GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addGap(161, 161, 161)
						.addComponent(jLabel1)
						.addContainerGap(GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addGap(32, 32, 32)
						.addComponent(jLabel1)
						.addContainerGap(54, Short.MAX_VALUE)));

		menuCadastro.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastro.text"));

		menuCadastroCliente.setAccelerator(getKeyStroke(KeyEvent.VK_C,
				InputEvent.CTRL_MASK));
		menuCadastroCliente.setIcon(new ImageIcon(
				getURLImage("cadastro_cliente.png"))); // NOI18N
		menuCadastroCliente.setMnemonic('C');
		menuCadastroCliente.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroCliente.text"));

		menuCadastro.add(menuCadastroCliente);

		menuCadastroFornecedor.setAccelerator(getKeyStroke(KeyEvent.VK_F,
				InputEvent.CTRL_MASK));
		menuCadastroFornecedor.setIcon(new ImageIcon(
				getURLImage("fornecedor.png"))); // NOI18N
		menuCadastroFornecedor.setMnemonic('F');
		menuCadastroFornecedor.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroFornecedor.text"));

		menuCadastro.add(menuCadastroFornecedor);

		menuCadastroContaBancaria.setAccelerator(getKeyStroke(KeyEvent.VK_B,
				InputEvent.CTRL_MASK));
		menuCadastroContaBancaria.setIcon(new ImageIcon(
				getURLImage("banco.png"))); // NOI18N
		menuCadastroContaBancaria.setMnemonic('B');
		menuCadastroContaBancaria.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroContaBancaria.text"));

		menuCadastro.add(menuCadastroContaBancaria);
		menuCadastro.add(jSeparator1);

		menuCadastroUnidade.setAccelerator(getKeyStroke(KeyEvent.VK_U,
				InputEvent.CTRL_MASK));
		menuCadastroUnidade.setIcon(new ImageIcon(getURLImage("unidade.png"))); // NOI18N
		menuCadastroUnidade.setMnemonic('U');
		menuCadastroUnidade.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroUnidade.text"));
		menuCadastro.add(menuCadastroUnidade);

		menuCadastroProduto.setAccelerator(getKeyStroke(KeyEvent.VK_O,
				InputEvent.CTRL_MASK));
		menuCadastroProduto.setIcon(new ImageIcon(getURLImage("produto.png"))); // NOI18N
		menuCadastroProduto.setMnemonic('o');
		menuCadastroProduto.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroProduto.text"));
		menuCadastro.add(menuCadastroProduto);
		menuCadastro.add(jSeparator2);

		menuCadastroDepartamento.setAccelerator(getKeyStroke(KeyEvent.VK_D,
				InputEvent.CTRL_MASK));
		menuCadastroDepartamento.setIcon(new ImageIcon(
				getURLImage("departamento.png"))); // NOI18N
		menuCadastroDepartamento.setMnemonic('D');
		menuCadastroDepartamento.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroDepartamento.text"));
		menuCadastro.add(menuCadastroDepartamento);

		menuCadastroFuncionario.setAccelerator(getKeyStroke(KeyEvent.VK_I,
				InputEvent.CTRL_MASK));
		menuCadastroFuncionario.setIcon(new ImageIcon(
				getURLImage("funcionario.png"))); // NOI18N
		menuCadastroFuncionario.setMnemonic('i');
		menuCadastroFuncionario.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroFuncionario.text"));
		menuCadastro.add(menuCadastroFuncionario);
		menuCadastro.add(jSeparator3);

		menuCadastroCartao.setAccelerator(getKeyStroke(KeyEvent.VK_A,
				InputEvent.CTRL_MASK));
		menuCadastroCartao.setIcon(new ImageIcon(getURLImage("cartao.png"))); // NOI18N
		menuCadastroCartao.setMnemonic('a');
		menuCadastroCartao.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroCartao.text"));

		menuCadastro.add(menuCadastroCartao);

		menuCadastroPlanoConta.setAccelerator(getKeyStroke(KeyEvent.VK_L,
				InputEvent.CTRL_MASK));
		menuCadastroPlanoConta.setIcon(new ImageIcon(
				getURLImage("plano_conta.png"))); // NOI18N
		menuCadastroPlanoConta.setMnemonic('l');
		menuCadastroPlanoConta.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroPlanoConta.text"));

		menuCadastro.add(menuCadastroPlanoConta);

		menuCadastroTipoPgtoRecebimento.setAccelerator(getKeyStroke(
				KeyEvent.VK_G, InputEvent.CTRL_MASK));
		menuCadastroTipoPgtoRecebimento.setIcon(new ImageIcon(
				getURLImage("tipo_pgto_recebimento.png"))); // NOI18N
		menuCadastroTipoPgtoRecebimento.setMnemonic('g');
		menuCadastroTipoPgtoRecebimento.setText(getBundleMessage().getMessage(
				"MenuView.menuCadastroTipoPgtoRecebimento.text"));

		menuCadastro.add(menuCadastroTipoPgtoRecebimento);
		menuCadastro.add(jSeparator4);

		menuSair.setAccelerator(getKeyStroke(KeyEvent.VK_X,
				InputEvent.CTRL_MASK));
		menuSair.setIcon(new ImageIcon(getURLImage("sair.png"))); // NOI18N
		menuSair.setText(getBundleMessage()
				.getMessage("MenuView.menuSair.text"));
		menuCadastro.add(menuSair);

		jMenuBar1.add(menuCadastro);

		menuMovimento.setText("Movimento");

		menuContasPagar.setAccelerator(getKeyStroke(KeyEvent.VK_P,
				InputEvent.CTRL_MASK));
		menuContasPagar.setIcon(new ImageIcon(getURLImage("contas_pagar.png"))); // NOI18N
		menuContasPagar.setMnemonic('P');
		menuContasPagar.setText(getBundleMessage().getMessage(
				"MenuView.menuContasPagar.text"));
		menuMovimento.add(menuContasPagar);

		menuContasReceber.setAccelerator(getKeyStroke(KeyEvent.VK_R,
				InputEvent.CTRL_MASK));
		menuContasReceber.setIcon(new ImageIcon(
				getURLImage("contas_receber.png"))); // NOI18N
		menuContasReceber.setMnemonic('R');
		menuContasReceber.setText(getBundleMessage().getMessage(
				"MenuView.menuContasReceber.text"));
		menuMovimento.add(menuContasReceber);

		menuVendas.setAccelerator(getKeyStroke(KeyEvent.VK_V,
				InputEvent.CTRL_MASK));
		menuVendas.setIcon(new ImageIcon(getURLImage("venda.png"))); // NOI18N
		menuVendas.setMnemonic('V');
		menuVendas.setText(getBundleMessage().getMessage(
				"MenuView.menuVendas.text"));
		menuMovimento.add(menuVendas);

		menuControleEstoque.setIcon(new ImageIcon(
				getURLImage("controle_estoque.png"))); // NOI18N
		menuControleEstoque.setText(getBundleMessage().getMessage(
				"MenuView.menuControleEstoque.text"));

		menuEntradaNF.setAccelerator(getKeyStroke(KeyEvent.VK_N,
				InputEvent.CTRL_MASK));
		menuEntradaNF.setIcon(new ImageIcon(getURLImage("nota_fiscal.png"))); // NOI18N
		menuEntradaNF.setMnemonic('N');
		menuEntradaNF.setText(getBundleMessage().getMessage(
				"MenuView.menuEntradaNF.text"));
		menuControleEstoque.add(menuEntradaNF);

		menuAtualizacaoPreco.setAccelerator(getKeyStroke(KeyEvent.VK_Z,
				InputEvent.CTRL_MASK));
		menuAtualizacaoPreco.setIcon(new ImageIcon(
				getURLImage("atualizacao_preco.png"))); // NOI18N
		menuAtualizacaoPreco.setMnemonic('z');
		menuAtualizacaoPreco.setText(getBundleMessage().getMessage(
				"MenuView.menuAtualizacaoPreco.text"));
		menuControleEstoque.add(menuAtualizacaoPreco);

		menuMovimento.add(menuControleEstoque);

		menuCompras.setIcon(new ImageIcon(getURLImage("compra.png"))); // NOI18N
		menuCompras.setText("Compras");

		menuRequisicao.setAccelerator(getKeyStroke(KeyEvent.VK_S,
				InputEvent.CTRL_MASK));
		menuRequisicao.setIcon(new ImageIcon(getURLImage("requisicao.png"))); // NOI18N
		menuRequisicao.setMnemonic('s');
		menuRequisicao.setText(getBundleMessage().getMessage(
				"MenuView.menuRequisicao.text"));
		menuCompras.add(menuRequisicao);

		menuCotacao.setAccelerator(getKeyStroke(KeyEvent.VK_T,
				InputEvent.CTRL_MASK));
		menuCotacao.setIcon(new ImageIcon(getURLImage("cotacao.png"))); // NOI18N
		menuCotacao.setMnemonic('t');
		menuCotacao.setText(getBundleMessage().getMessage(
				"MenuView.menuCotacao.text"));
		menuCompras.add(menuCotacao);

		menuConfirmacaoCotacao.setAccelerator(getKeyStroke(KeyEvent.VK_J,
				InputEvent.CTRL_MASK));
		menuConfirmacaoCotacao.setIcon(new ImageIcon(
				getURLImage("confirma.png"))); // NOI18N
		menuConfirmacaoCotacao.setText(getBundleMessage().getMessage(
				"MenuView.menuConfirmacaoCotacao.text"));
		menuCompras.add(menuConfirmacaoCotacao);

		menuPedido.setAccelerator(getKeyStroke(KeyEvent.VK_E,
				InputEvent.CTRL_MASK));
		menuPedido.setIcon(new ImageIcon(getURLImage("pedido.png"))); // NOI18N
		menuPedido.setMnemonic('e');
		menuPedido.setText(getBundleMessage().getMessage(
				"MenuView.menuPedido.text"));
		menuCompras.add(menuPedido);

		menuMovimento.add(menuCompras);

		menuTesourariaBanco.setIcon(new ImageIcon(
				getURLImage("tesouraria_banco.png"))); // NOI18N
		menuTesourariaBanco.setText(getBundleMessage().getMessage(
				"MenuView.menuTesourariaBanco.text"));

		menuEmissaoCheques.setAccelerator(getKeyStroke(KeyEvent.VK_H,
				InputEvent.CTRL_MASK));
		menuEmissaoCheques.setIcon(new ImageIcon(getURLImage("cheque.png"))); // NOI18N
		menuEmissaoCheques.setMnemonic('h');
		menuEmissaoCheques.setText(getBundleMessage().getMessage(
				"MenuView.menuEmissaoCheques.text"));
		menuTesourariaBanco.add(menuEmissaoCheques);

		menuConciliacaoCheques.setAccelerator(getKeyStroke(KeyEvent.VK_Q,
				InputEvent.CTRL_MASK));
		menuConciliacaoCheques.setIcon(new ImageIcon(
				getURLImage("conciliacao_bancaria.png"))); // NOI18N
		menuConciliacaoCheques.setMnemonic('q');
		menuConciliacaoCheques.setText(getBundleMessage().getMessage(
				"MenuView.menuConciliacaoCheques.text"));
		menuTesourariaBanco.add(menuConciliacaoCheques);

		menuMovimentoBanco.setAccelerator(getKeyStroke(KeyEvent.VK_M,
				InputEvent.CTRL_MASK));
		menuMovimentoBanco.setIcon(new ImageIcon(getURLImage("banco.png"))); // NOI18N
		menuMovimentoBanco.setMnemonic('M');
		menuMovimentoBanco.setText(getBundleMessage().getMessage(
				"MenuView.menuMovimentoBanco.text"));
		menuTesourariaBanco.add(menuMovimentoBanco);

		menuMovimento.add(menuTesourariaBanco);

		jMenuBar1.add(menuMovimento);

		menuUltilitarios.setText(getBundleMessage().getMessage(
				"MenuView.menuUltilitarios.text"));

		menuCalculadora.setAccelerator(getKeyStroke(KeyEvent.VK_F2, 0));
		menuCalculadora.setIcon(new ImageIcon(getURLImage("calculadora.png"))); // NOI18N
		menuCalculadora.setText(getBundleMessage().getMessage(
				"MenuView.menuCalculadora.text"));
		menuUltilitarios.add(menuCalculadora);

		menuCalendario.setAccelerator(getKeyStroke(KeyEvent.VK_F3, 0));
		menuCalendario.setIcon(new ImageIcon(getURLImage("calendario.png"))); // NOI18N
		menuCalendario.setText(getBundleMessage().getMessage(
				"MenuView.menuCalendario.text"));
		menuUltilitarios.add(menuCalendario);
		menuUltilitarios.add(jSeparator5);

		menuSeguranca.setIcon(new ImageIcon(getURLImage("seguranca.png"))); // NOI18N
		menuSeguranca.setText(getBundleMessage().getMessage(
				"MenuView.menuSeguranca.text"));

		menuSenha.setAccelerator(getKeyStroke(KeyEvent.VK_F10, 0));
		menuSenha.setIcon(new ImageIcon(getURLImage("senha.png"))); // NOI18N
		menuSenha.setText(getBundleMessage().getMessage(
				"MenuView.menuSenha.text"));
		menuSeguranca.add(menuSenha);

		menuNivelAcesso.setAccelerator(getKeyStroke(KeyEvent.VK_F12, 0));
		menuNivelAcesso.setIcon(new ImageIcon(getURLImage("nivel_acesso.png"))); // NOI18N
		menuNivelAcesso.setText(getBundleMessage().getMessage(
				"MenuView.menuNivelAcesso.text"));
		menuSeguranca.add(menuNivelAcesso);

		menuUltilitarios.add(menuSeguranca);

		jMenuBar1.add(menuUltilitarios);

		menuAjuda.setText(getBundleMessage().getMessage(
				"MenuView.menuAjuda.text"));

		menuSobre.setAccelerator(getKeyStroke(KeyEvent.VK_F1, 0));
		menuSobre.setIcon(new ImageIcon(getURLImage("erp.png"))); // NOI18N
		menuSobre.setText(getBundleMessage().getMessage(
				"MenuView.menuSobre.text"));
		menuAjuda.add(menuSobre);

		jMenuBar1.add(menuAjuda);

		setJMenuBar(jMenuBar1);

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE,
						GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE,
						GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		setSize(new java.awt.Dimension(640, 480));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private URL getURLImage(String img) {
		URL imageURL = ApplicationUtil.getURLImage(this.getClass(), img);
		return imageURL;
	}

	public JButton getBtnCadastroCliente() {
		return btnCadastroCliente;
	}

	public JButton getBtnCadastroFornecedor() {
		return btnCadastroFornecedor;
	}

	public JButton getBtnCadastroProduto() {
		return btnCadastroProduto;
	}

	public JButton getBtnContasPagar() {
		return btnContasPagar;
	}

	public JButton getBtnContasReceber() {
		return btnContasReceber;
	}

	public JButton getBtnSair() {
		return btnSair;
	}

	public JMenuItem getMenuAtualizacaoPreco() {
		return menuAtualizacaoPreco;
	}

	public JMenuItem getMenuCadastroCartao() {
		return menuCadastroCartao;
	}

	public JMenuItem getMenuCadastroCliente() {
		return menuCadastroCliente;
	}

	public JMenuItem getMenuCadastroContaBancaria() {
		return menuCadastroContaBancaria;
	}

	public JMenuItem getMenuCadastroDepartamento() {
		return menuCadastroDepartamento;
	}

	public JMenuItem getMenuCadastroFornecedor() {
		return menuCadastroFornecedor;
	}

	public JMenuItem getMenuCadastroFuncionario() {
		return menuCadastroFuncionario;
	}

	public JMenuItem getMenuCadastroPlanoConta() {
		return menuCadastroPlanoConta;
	}

	public JMenuItem getMenuCadastroProduto() {
		return menuCadastroProduto;
	}

	public JMenuItem getMenuCadastroTipoPgtoRecebimento() {
		return menuCadastroTipoPgtoRecebimento;
	}

	public JMenuItem getMenuCadastroUnidade() {
		return menuCadastroUnidade;
	}

	public JMenuItem getMenuCalculadora() {
		return menuCalculadora;
	}

	public JMenuItem getMenuCalendario() {
		return menuCalendario;
	}

	public JMenuItem getMenuConciliacaoCheques() {
		return menuConciliacaoCheques;
	}

	public JMenuItem getMenuConfirmacaoCotacao() {
		return menuConfirmacaoCotacao;
	}

	public JMenuItem getMenuContasPagar() {
		return menuContasPagar;
	}

	public JMenuItem getMenuContasReceber() {
		return menuContasReceber;
	}

	public JMenuItem getMenuCotacao() {
		return menuCotacao;
	}

	public JMenuItem getMenuEmissaoCheques() {
		return menuEmissaoCheques;
	}

	public JMenuItem getMenuEntradaNF() {
		return menuEntradaNF;
	}

	public JMenuItem getMenuMovimentoBanco() {
		return menuMovimentoBanco;
	}

	public JMenuItem getMenuNivelAcesso() {
		return menuNivelAcesso;
	}

	public JMenuItem getMenuPedido() {
		return menuPedido;
	}

	public JMenuItem getMenuRequisicao() {
		return menuRequisicao;
	}

	public JMenuItem getMenuSair() {
		return menuSair;
	}

	public JMenuItem getMenuSenha() {
		return menuSenha;
	}

	public JMenuItem getMenuVendas() {
		return menuVendas;
	}

	public MenuAjuda getMenuAjuda() {
		return menuAjuda;
	}

	public JMenuItem getMenuSobre() {
		return menuSobre;
	}

	protected AppResourceBundleMessage getBundleMessage() {
		return bundleMessage;
	}

}
