--DML – Data Manipulation Language ( DML) são utilizados para o gerenciamento de dados dentro de objetos do banco. Alguns exemplos:
--SELECT- recuperar dados do banco de dados
--INSERT – inserir dados em uma tabela
--UPDATE – atualiza os dados existentes em uma tabela
--DELETE – exclui registros de uma tabela,
--CALL – chamar um subprograma PL / SQL
--EXPLAIN PLAN – explicar o caminho de acesso aos dados
--LOCK TABLE – controle de concorrência

insert into banco(cod_banco, nome_banco, site_banco) values('654', 'Banco A.J.Renner S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('246', 'Banco ABC Brasil S.A.', 'www.abcbrasil.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('025', 'Banco Alfa S.A.', 'www.bancoalfa.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('641', 'Banco Alvorada S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('213', 'Banco Arbi S.A.', 'www.arbi.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('019', 'Banco Azteca do Brasil S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('029', 'Banco Banerj S.A.', 'www.banerj.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('000', 'Banco Bankpar S.A.', 'www.aexp.com');
insert into banco(cod_banco, nome_banco, site_banco) values('740', 'Banco Barclays S.A.', 'www.barclays.com');
insert into banco(cod_banco, nome_banco, site_banco) values('107', 'Banco BBM S.A.', 'www.bbmbank.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('031', 'Banco Beg S.A.', 'www.itau.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('739', 'Banco BGN S.A.', 'www.bgn.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('096', 'Banco BM&F de Servicos de Liquidacao e Custodia S.A.', 'www.bmf.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('318', 'Banco BMG S.A.', 'www.bancobmg.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('752', 'Banco BNP Paribas Brasil S.A.', 'www.bnpparibas.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('248', 'Banco Boavista Interatlantico S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('218', 'Banco Bonsucesso S.A.', 'www.bancobonsucesso.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('065', 'Banco Bracce S.A.', 'www.lemon.com');
insert into banco(cod_banco, nome_banco, site_banco) values('036', 'Banco Bradesco BBI S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('204', 'Banco Bradesco Cartoes S.A.', 'www.iamex.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('394', 'Banco Bradesco Financiamentos S.A.', 'www.bmc.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('237', 'Banco Bradesco S.A.', 'www.bradesco.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('225', 'Banco Brascan S.A.', 'www.bancobrascan.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M15', 'Banco BRJ S.A.', 'www.brjbank.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('208', 'Banco BTG Pactual S.A.', 'www.pactual.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('044', 'Banco BVA S.A.', 'www.bancobva.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('263', 'Banco Cacique S.A.', 'www.bancocacique.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('473', 'Banco Caixa Geral - Brasil S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('412', 'Banco Capital S.A.', 'www.bancocapital.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('040', 'Banco Cargill S.A.', 'www.bancocargill.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('745', 'Banco Citibank S.A.', 'www.citibank.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M08', 'Banco Citicard S.A.', 'www.credicardbanco.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('241', 'Banco Classico S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('M19', 'Banco CNH Capital S.A.', 'www.bancocnh.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('215', 'Banco Comercial e de Investimento Sudameris S.A.', 'www.sudameris.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('756', 'Banco Cooperativo do Brasil S.A. - BANCOOB', 'www.bancoob.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('748', 'Banco Cooperativo Sicredi S.A.', 'www.sicredi.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('075', 'Banco CR2 S.A.', 'www.bancocr2.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('721', 'Banco Credibel S.A.', 'www.credibel.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('222', 'Banco Credit Agricole Brasil S.A.', 'www.calyon.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('505', 'Banco Credit Suisse (Brasil) S.A.', 'www.csfb.com');
insert into banco(cod_banco, nome_banco, site_banco) values('229', 'Banco Cruzeiro do Sul S.A.', 'www.bcsul.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('266', 'Banco Cedula S.A.', 'www.bancocedula.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('003', 'Banco da Amazonia S.A.', 'www.bancoamazonia.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('083-3', 'Banco da China Brasil S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('M21', 'Banco Daimlerchrysler S.A.', 'www.bancodaimlerchrysler.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('707', 'Banco Daycoval S.A.', 'www.daycoval.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('300', 'Banco de La Nacion Argentina', 'www.bna.com.ar');
insert into banco(cod_banco, nome_banco, site_banco) values('495', 'Banco de La Provincia de Buenos Aires', 'www.bapro.com.ar');
insert into banco(cod_banco, nome_banco, site_banco) values('494', 'Banco de La Republica Oriental del Uruguay', '');
insert into banco(cod_banco, nome_banco, site_banco) values('M06', 'Banco de Lage Landen Brasil S.A.', 'www.delagelanden.com');
insert into banco(cod_banco, nome_banco, site_banco) values('024', 'Banco de Pernambuco S.A. - BANDEPE', 'www.bandepe.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('456', 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.', 'www.btm.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('214', 'Banco Dibens S.A.', 'www.bancodibens.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('001', 'Banco do Brasil S.A.', 'www.bb.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('047', 'Banco do Estado de Sergipe S.A.', 'www.banese.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('037', 'Banco do Estado do Para S.A.', 'www.banparanet.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('039', 'Banco do Estado do Piaui S.A. - BEP', 'www.bep.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('041', 'Banco do Estado do Rio Grande do Sul S.A.', 'www.banrisul.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('004', 'Banco do Nordeste do Brasil S.A.', 'www.banconordeste.gov.br');
insert into banco(cod_banco, nome_banco, site_banco) values('265', 'Banco Fator S.A.', 'www.bancofator.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M03', 'Banco Fiat S.A.', 'www.bancofiat.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('224', 'Banco Fibra S.A.', 'www.bancofibra.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('626', 'Banco Ficsa S.A.', 'www.ficsa.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M18', 'Banco Ford S.A.', 'www.bancoford.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('233', 'Banco GE Capital S.A.', 'www.ge.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('734', 'Banco Gerdau S.A.', 'www.bancogerdau.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M07', 'Banco GMAC S.A.', 'www.bancogm.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('612', 'Banco Guanabara S.A.', 'www.bcoguan.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M22', 'Banco Honda S.A.', 'www.bancohonda.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('063', 'Banco Ibi S.A. Banco Multiplo', 'www.ibi.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M11', 'Banco IBM S.A.', 'www.ibm.com/br/financing/');
insert into banco(cod_banco, nome_banco, site_banco) values('604', 'Banco Industrial do Brasil S.A.', 'www.bancoindustrial.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('320', 'Banco Industrial e Comercial S.A.', 'www.bicbanco.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('653', 'Banco Indusval S.A.', 'www.indusval.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('630', 'Banco Intercap S.A.', 'www.intercap.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('077-9', 'Banco Intermedium S.A.', 'www.intermedium.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('249', 'Banco Investcred Unibanco S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('M09', 'Banco Itaucred Financiamentos S.A.', 'www.itaucred.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('184', 'Banco Itau BBA S.A.', 'www.itaubba.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('479', 'Banco ItauBank S.A.', 'www.itaubank.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('376', 'Banco J. P. Morgan S.A.', 'www.jpmorgan.com');
insert into banco(cod_banco, nome_banco, site_banco) values('074', 'Banco J. Safra S.A.', 'www.jsafra.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('217', 'Banco John Deere S.A.', 'www.johndeere.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('076', 'Banco KDB S.A.', 'www.bancokdb.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('757', 'Banco KEB do Brasil S.A.', 'www.bancokeb.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('600', 'Banco Luso Brasileiro S.A.', 'www.lusobrasileiro.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('212', 'Banco Matone S.A.', 'www.bancomatone.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M12', 'Banco Maxinvest S.A.', 'www.bancomaxinvest.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('389', 'Banco Mercantil do Brasil S.A.', 'www.mercantil.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('746', 'Banco Modal S.A.', 'www.bancomodal.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M10', 'Banco Moneo S.A.', 'www.bancomoneo.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('738', 'Banco Morada S.A.', 'www.bancomorada.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('066', 'Banco Morgan Stanley S.A.', 'www.morganstanley.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('243', 'Banco Maxima S.A.', 'www.bancomaxima.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('045', 'Banco Opportunity S.A.', 'www.opportunity.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M17', 'Banco Ourinvest S.A.', 'www.ourinvest.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('623', 'Banco Panamericano S.A.', 'www.panamericano.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('611', 'Banco Paulista S.A.', 'www.bancopaulista.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('613', 'Banco Pecunia S.A.', 'www.bancopecunia.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('094-2', 'Banco Petra S.A.', 'www.personaltrader.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('643', 'Banco Pine S.A.', 'www.bancopine.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('724', 'Banco Porto Seguro S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('735', 'Banco Pottencial S.A.', 'www.pottencial.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('638', 'Banco Prosper S.A.', 'www.bancoprosper.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M24', 'Banco PSA Finance Brasil S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('747', 'Banco Rabobank International Brasil S.A.', 'www.rabobank.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('088-4', 'Banco Randon S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('356', 'Banco Real S.A.', 'www.bancoreal.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('633', 'Banco Rendimento S.A.', 'www.rendimento.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('741', 'Banco Ribeirao Preto S.A.', 'www.brp.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M16', 'Banco Rodobens S.A.', 'www.rodobens.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('072', 'Banco Rural Mais S.A.', 'www.rural.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('453', 'Banco Rural S.A.', 'www.rural.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('422', 'Banco Safra S.A.', 'www.safra.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('033', 'Banco Santander (Brasil) S.A.', 'www.santander.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('250', 'Banco Schahin S.A.', 'www.bancoschahin.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('743', 'Banco Semear S.A.', 'www.bancosemear.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('749', 'Banco Simples S.A.', 'www.bancosimples.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('366', 'Banco Societe Generale Brasil S.A.', 'www.sgbrasil.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('637', 'Banco Sofisa S.A.', 'www.sofisa.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('012', 'Banco Standard de Investimentos S.A.', 'www.standardbank.com');
insert into banco(cod_banco, nome_banco, site_banco) values('464', 'Banco Sumitomo Mitsui Brasileiro S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('082-5', 'Banco Topazio S.A.', 'www.bancotopazio.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M20', 'Banco Toyota do Brasil S.A.', 'www.bancotoyota.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M13', 'Banco Tricury S.A.', 'www.tricury.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('634', 'Banco Triangulo S.A.', 'www.tribanco.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M14', 'Banco Volkswagen S.A.', 'www.bancovw.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('M23', 'Banco Volvo (Brasil) S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('655', 'Banco Votorantim S.A.', 'www.bancovotorantim.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('610', 'Banco VR S.A.', 'www.vr.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('370', 'Banco WestLB do Brasil S.A.', 'www.westlb.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('021', 'BANESTES S.A. Banco do Estado do Espirito Santo', 'www.banestes.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('719', 'Banif-Banco Internacional do Funchal (Brasil)S.A.', 'www.banif.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('755', 'Bank of America Merrill Lynch Banco Multiplo S.A.', 'www.ml.com');
insert into banco(cod_banco, nome_banco, site_banco) values('744', 'BankBoston N.A.', 'www.bankboston.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('073', 'BB Banco Popular do Brasil S.A.', 'www.bancopopulardobrasil.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('078', 'BES Investimento do Brasil S.A.-Banco de Investimento', 'www.besinvestimento.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('069', 'BPN Brasil Banco Multiplo S.A.', 'www.bpnbrasil.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('070', 'BRB - Banco de Brasilia S.A.', 'www.brb.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('092-2', 'Brickell S.A. Credito, financiamento e Investimento', '');
insert into banco(cod_banco, nome_banco, site_banco) values('104', 'Caixa Economica Federal', 'www.caixa.gov.br');
insert into banco(cod_banco, nome_banco, site_banco) values('477', 'Citibank N.A.', 'www.citibank.com/brasil');
insert into banco(cod_banco, nome_banco, site_banco) values('081-7', 'Concordia Banco S.A.', 'www.concordiabanco.com');
insert into banco(cod_banco, nome_banco, site_banco) values('097-3', 'Cooperativa Central de Credito Noroeste Brasileiro Ltda.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('085-x', 'Cooperativa Central de Credito Urbano-CECRED', '');
insert into banco(cod_banco, nome_banco, site_banco) values('099-x', 'Cooperativa Central de Economia e Credito Mutuo das Unicreds', '');
insert into banco(cod_banco, nome_banco, site_banco) values('090-2', 'Cooperativa Central de Economia e Credito Mutuo das Unicreds', '');
insert into banco(cod_banco, nome_banco, site_banco) values('089-2', 'Cooperativa de Credito Rural da Regiao de Mogiana', '');
insert into banco(cod_banco, nome_banco, site_banco) values('087-6', 'Cooperativa Unicred Central Santa Catarina', '');
insert into banco(cod_banco, nome_banco, site_banco) values('098-1', 'Credicorol Cooperativa de Credito Rural', '');
insert into banco(cod_banco, nome_banco, site_banco) values('487', 'Deutsche Bank S.A. - Banco Alemao', 'www.deutsche-bank.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('751', 'Dresdner Bank Brasil S.A. - Banco Multiplo', 'www.dkib.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('064', 'Goldman Sachs do Brasil Banco Multiplo S.A.', 'www.goldmansachs.com');
insert into banco(cod_banco, nome_banco, site_banco) values('062', 'Hipercard Banco Multiplo S.A.', 'www.hipercard.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('399', 'HSBC Bank Brasil S.A. - Banco Multiplo', 'www.hsbc.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('168', 'HSBC Finance (Brasil) S.A. - Banco Multiplo', '');
insert into banco(cod_banco, nome_banco, site_banco) values('492', 'ING Bank N.V.', 'www.ing.com');
insert into banco(cod_banco, nome_banco, site_banco) values('652', 'Itau Unibanco Holding S.A.', 'www.itau.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('341', 'Itau Unibanco S.A.', 'www.itau.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('079', 'JBS Banco S.A.', 'www.bancojbs.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('488', 'JPMorgan Chase Bank', 'www.jpmorganchase.com');
insert into banco(cod_banco, nome_banco, site_banco) values('014', 'Natixis Brasil S.A. Banco Multiplo', '');
insert into banco(cod_banco, nome_banco, site_banco) values('753', 'NBC Bank Brasil S.A. - Banco Multiplo', 'www.nbcbank.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('086-8', 'OBOE Credito Financiamento e Investimento S.A.', '');
insert into banco(cod_banco, nome_banco, site_banco) values('254', 'Parana Banco S.A.', 'www.paranabanco.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('409', 'UNIBANCO - Uniao de Bancos Brasileiros S.A.', 'www.unibanco.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('230', 'Unicard Banco Multiplo S.A.', 'www.unicard.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('091-4', 'Unicred Central do Rio Grande do Sul', 'www.unicred-rs.com.br');
insert into banco(cod_banco, nome_banco, site_banco) values('084', 'Unicred Norte do Parana', '');


select * from public.banco ;