--Tabela de Juros dos Cartões de Credito
--http://www.anucc.org.br/servicos/index/25

insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'American Express Card',                   'PayFlex 5,5%',   100, 11.9,  2,    'TOTAL',  1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'American Express Credit',                 '5,95% a 10,95%', 20,  11.95, 2,    'TOTAL',  1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'American Express Platinum',               'PayFlex 5,5%',   20,  11.9,  2,    'TOTAL',  1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Bandeirantes MasterCard',                 '10,9%',          20,  10.8,  2,    'TOTAL',  1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Bandeirantes Texaco Domestico Visa',      '12,94%',         20,  10,    2,    'MINIMO', 1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Bandeirantes Texaco Internacional Visa',  '11,95%',         20,  10,    2,    'MINIMO', 1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Bandeirantes Texaco Gold Visa',           '8,95%',          20,  10,    2,    'MINIMO', 1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Banerj Visa',                             '11,7%',          20,  10.38, 2,    'MINIMO', 5);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Baneb Visa',                              '10%',            20,  10,    2,    'TOTAL',  7);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Banespa Visa Classic',                    '10,45%',         20,  10.42, 2,    'TOTAL',  1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Banespa Visa Gold',                       '5,4%',           20,  10.42, 2,    'TOTAL',  1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Banestes Visa Internacional',             '9,5%',           25,  7.5,   2,    'MINIMO', 5);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Banrisul Visa',                           '9,95%',          25,  9.95,  2,    'MINIMO', 5);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Boston Visa',                             '13%',            20,  9,     2,    'TOTAL',  1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Boston Visa Platrinum',                   '13%',            20,  9,     2,    'TOTAL',  1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Bradesco Visa/MasterCard Domestico',      '11,25%',         10,  10.5,  null, 'TOTAL',     null);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Bradesco Visa /MasterCard Internacional', '11,2%',          14,  10.5,  null, 'TOTAL',     null);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Bradesco Visa/MasterCard Gold',           '10,6%',          10,  10.5,  null, 'TOTAL',     null);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Bradesco Diners',                         '13%',            10,  10.8,  2,    'TOTAL',  1);
insert into cartao_credito(id_cartao_credito, empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values(nextval('cartao_credito_seq'), 'Bradesco Platinum',                       '5,5%',           10,  8.5,   null, 'TOTAL',     null);

select * from public.cartao_credito; 